- name: Ensure init.d script for update-daemon is disabled
  ansible.builtin.service:
    name: tt-rss
    enabled: false
    state: stopped
  tags:
    - ttrss
    - backend

- name: Install ttrss update service in systemd
  ansible.builtin.template:
    src: ttrss.service.j2
    dest: "{{ ttrss_systemd_target_dir }}/ttrss.service"
    mode: 0644
  register: service_template
  notify:
    - Reload systemd
  tags:
    - ttrss
    - backend

- name: Enable and start ttrss update service
  ansible.builtin.systemd:
    name: ttrss
    enabled: true
    state: started
  tags:
    - ttrss
    - backend
