- name: "Ensure checkout plugin {{ plugin.name }}"
  ansible.builtin.git: # noqa ignore-errors git-latest
    repo: "{{ plugin.url }}"
    dest: "{{ ttrss_install_path }}/{{ ttrss_plugins_base_path }}/{{ plugin.name }}"
    depth: 1
    update: true
    force: true
  ignore_errors: true
  tags:
    - ttrss
