---
# handlers file for tt-rss
- name: Restart lighttpd
  ansible.builtin.service:
    name: lighttpd
    state: restarted

- name: Restart tt-rss daemon
  ansible.builtin.service:
    name: tt-rss
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
    no_block: false
